"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
// Expose typed API to renderer
electron_1.contextBridge.exposeInMainWorld('electronAPI', {
    // ─── Platform info ──────────────────────────────────────────────
    platform: process.platform, // 'darwin' | 'win32' | 'linux'
    // ─── Window Controls ─────────────────────────────────────────────
    window: {
        minimize: () => electron_1.ipcRenderer.send('window:minimize'),
        maximize: () => electron_1.ipcRenderer.send('window:maximize'),
        close: () => electron_1.ipcRenderer.send('window:close'),
        quit: () => electron_1.ipcRenderer.send('window:quit'),
        isMaximized: () => electron_1.ipcRenderer.invoke('window:isMaximized'),
    },
    // ─── Shell ───────────────────────────────────────────────────────
    shell: {
        openExternal: (url) => electron_1.ipcRenderer.send('shell:openExternal', url),
        openPath: (filePath) => electron_1.ipcRenderer.invoke('shell:openPath', filePath),
        openInApp: (url) => electron_1.ipcRenderer.invoke('shell:openInApp', url),
    },
    // ─── Util ───────────────────────────────────────────────────────
    util: {
        fetchUrl: (args) => electron_1.ipcRenderer.invoke('util:fetchUrl', args),
    },
    // ─── Login / Account ─────────────────────────────────────────────
    login: {
        loginQR: (tempId) => electron_1.ipcRenderer.invoke('login:qr', { tempId }),
        loginQRAbort: (tempId) => electron_1.ipcRenderer.invoke('login:qr:abort', { tempId }),
        loginCookies: (imei, cookies, userAgent) => electron_1.ipcRenderer.invoke('login:cookies', { imei, cookies, userAgent }),
        loginAuth: (authJson) => electron_1.ipcRenderer.invoke('login:auth', { authJson }),
        connectAccount: (auth) => electron_1.ipcRenderer.invoke('login:connect', { auth }),
        disconnectAccount: (zaloId) => electron_1.ipcRenderer.invoke('login:disconnect', { zaloId }),
        disconnectAll: () => electron_1.ipcRenderer.invoke('login:disconnectAll'),
        getAccounts: () => electron_1.ipcRenderer.invoke('login:getAccounts'),
        removeAccount: (zaloId) => electron_1.ipcRenderer.invoke('login:removeAccount', { zaloId }),
        checkHealth: (zaloIds) => electron_1.ipcRenderer.invoke('login:checkHealth', { zaloIds }),
        requestOldMessages: (zaloId) => electron_1.ipcRenderer.invoke('login:requestOldMessages', { zaloId }),
    },
    // ─── Zalo API ────────────────────────────────────────────────────
    zalo: {
        sendMessage: (params) => electron_1.ipcRenderer.invoke('zalo:sendMessage', params),
        sendImage: (params) => electron_1.ipcRenderer.invoke('zalo:sendImage', params),
        sendImages: (params) => electron_1.ipcRenderer.invoke('zalo:sendImages', params),
        sendFile: (params) => electron_1.ipcRenderer.invoke('zalo:sendFile', params),
        sendSticker: (params) => electron_1.ipcRenderer.invoke('zalo:sendSticker', params),
        sendVoice: (params) => electron_1.ipcRenderer.invoke('zalo:sendVoice', params),
        sendVideo: (params) => electron_1.ipcRenderer.invoke('zalo:sendVideo', params),
        sendLink: (params) => electron_1.ipcRenderer.invoke('zalo:sendLink', params),
        sendCard: (params) => electron_1.ipcRenderer.invoke('zalo:sendCard', params),
        undoMessage: (params) => electron_1.ipcRenderer.invoke('zalo:undoMessage', params),
        deleteMessage: (params) => electron_1.ipcRenderer.invoke('zalo:deleteMessage', params),
        deleteChat: (params) => electron_1.ipcRenderer.invoke('zalo:deleteChat', params),
        addReaction: (params) => electron_1.ipcRenderer.invoke('zalo:addReaction', params),
        forwardMessage: (params) => electron_1.ipcRenderer.invoke('zalo:forwardMessage', params),
        getFriends: (auth) => electron_1.ipcRenderer.invoke('zalo:getFriends', { auth }),
        getGroups: (auth) => electron_1.ipcRenderer.invoke('zalo:getGroups', { auth }),
        getUserInfo: (params) => electron_1.ipcRenderer.invoke('zalo:getUserInfo', params),
        getContext: (params) => electron_1.ipcRenderer.invoke('zalo:getContext', params),
        findUser: (params) => electron_1.ipcRenderer.invoke('zalo:findUser', params),
        sendFriendRequest: (params) => electron_1.ipcRenderer.invoke('zalo:sendFriendRequest', params),
        acceptFriendRequest: (params) => electron_1.ipcRenderer.invoke('zalo:acceptFriendRequest', params),
        rejectFriendRequest: (params) => electron_1.ipcRenderer.invoke('zalo:rejectFriendRequest', params),
        undoFriendRequest: (params) => electron_1.ipcRenderer.invoke('zalo:undoFriendRequest', params),
        removeFriend: (params) => electron_1.ipcRenderer.invoke('zalo:removeFriend', params),
        getSentFriendRequests: (auth) => electron_1.ipcRenderer.invoke('zalo:getSentFriendRequests', { auth }),
        getFriendRequestStatus: (params) => electron_1.ipcRenderer.invoke('zalo:getFriendRequestStatus', params),
        getFriendRecommendations: (auth) => electron_1.ipcRenderer.invoke('zalo:getFriendRecommendations', { auth }),
        getAliasList: (params) => electron_1.ipcRenderer.invoke('zalo:getAliasList', params),
        blockUser: (params) => electron_1.ipcRenderer.invoke('zalo:blockUser', params),
        unblockUser: (params) => electron_1.ipcRenderer.invoke('zalo:unblockUser', params),
        getRelatedFriendGroup: (params) => electron_1.ipcRenderer.invoke('zalo:getRelatedFriendGroup', params),
        createGroup: (params) => electron_1.ipcRenderer.invoke('zalo:createGroup', params),
        getGroupInfo: (params) => electron_1.ipcRenderer.invoke('zalo:getGroupInfo', params),
        addUserToGroup: (params) => electron_1.ipcRenderer.invoke('zalo:addUserToGroup', params),
        removeUserFromGroup: (params) => electron_1.ipcRenderer.invoke('zalo:removeUserFromGroup', params),
        leaveGroup: (params) => electron_1.ipcRenderer.invoke('zalo:leaveGroup', params),
        changeGroupName: (params) => electron_1.ipcRenderer.invoke('zalo:changeGroupName', params),
        changeGroupAvatar: (params) => electron_1.ipcRenderer.invoke('zalo:changeGroupAvatar', params),
        changeGroupOwner: (params) => electron_1.ipcRenderer.invoke('zalo:changeGroupOwner', params),
        disperseGroup: (params) => electron_1.ipcRenderer.invoke('zalo:disperseGroup', params),
        addGroupDeputy: (params) => electron_1.ipcRenderer.invoke('zalo:addGroupDeputy', params),
        removeGroupDeputy: (params) => electron_1.ipcRenderer.invoke('zalo:removeGroupDeputy', params),
        getGroupMembersInfo: (params) => electron_1.ipcRenderer.invoke('zalo:getGroupMembersInfo', params),
        addGroupBlockedMember: (params) => electron_1.ipcRenderer.invoke('zalo:addGroupBlockedMember', params),
        removeGroupBlockedMember: (params) => electron_1.ipcRenderer.invoke('zalo:removeGroupBlockedMember', params),
        getGroupBlockedMember: (params) => electron_1.ipcRenderer.invoke('zalo:getGroupBlockedMember', params),
        inviteUserToGroups: (params) => electron_1.ipcRenderer.invoke('zalo:inviteUserToGroups', params),
        updateGroupSettings: (params) => electron_1.ipcRenderer.invoke('zalo:updateGroupSettings', params),
        getGroupLinkDetail: (params) => electron_1.ipcRenderer.invoke('zalo:getGroupLinkDetail', params),
        getGroupLinkInfo: (params) => electron_1.ipcRenderer.invoke('zalo:getGroupLinkInfo', params),
        enableGroupLink: (params) => electron_1.ipcRenderer.invoke('zalo:enableGroupLink', params),
        disableGroupLink: (params) => electron_1.ipcRenderer.invoke('zalo:disableGroupLink', params),
        getPendingGroupMembers: (params) => electron_1.ipcRenderer.invoke('zalo:getPendingGroupMembers', params),
        getMessageHistory: (params) => electron_1.ipcRenderer.invoke('zalo:getMessageHistory', params),
        getGroupChatHistory: (params) => electron_1.ipcRenderer.invoke('zalo:getGroupChatHistory', params),
        getPinConversations: (auth) => electron_1.ipcRenderer.invoke('zalo:getPinConversations', { auth }),
        setPinConversation: (params) => electron_1.ipcRenderer.invoke('zalo:setPinConversation', params),
        setMute: (params) => electron_1.ipcRenderer.invoke('zalo:setMute', params),
        keepAlive: (auth) => electron_1.ipcRenderer.invoke('zalo:keepAlive', { auth }),
        getLabels: (params) => electron_1.ipcRenderer.invoke('zalo:getLabels', params),
        updateLabels: (params) => electron_1.ipcRenderer.invoke('zalo:updateLabels', params),
        changeFriendAlias: (params) => electron_1.ipcRenderer.invoke('zalo:changeFriendAlias', params),
        getStickers: (params) => electron_1.ipcRenderer.invoke('zalo:getStickers', params),
        getStickersDetail: (params) => electron_1.ipcRenderer.invoke('zalo:getStickersDetail', params),
        getStickerCategoryDetail: (params) => electron_1.ipcRenderer.invoke('zalo:getStickerCategoryDetail', params),
        addUnreadMark: (params) => electron_1.ipcRenderer.invoke('zalo:addUnreadMark', params),
        removeUnreadMark: (params) => electron_1.ipcRenderer.invoke('zalo:removeUnreadMark', params),
        createPoll: (params) => electron_1.ipcRenderer.invoke('zalo:createPoll', params),
        getPollDetail: (params) => electron_1.ipcRenderer.invoke('zalo:getPollDetail', params),
        lockPoll: (params) => electron_1.ipcRenderer.invoke('zalo:lockPoll', params),
        doVotePoll: (params) => electron_1.ipcRenderer.invoke('zalo:doVotePoll', params),
        addPollOption: (params) => electron_1.ipcRenderer.invoke('zalo:addPollOption', params),
        uploadVideoThumb: (params) => electron_1.ipcRenderer.invoke('zalo:uploadVideoThumb', params),
        uploadVideoFile: (params) => electron_1.ipcRenderer.invoke('zalo:uploadVideoFile', params),
        uploadVoiceFile: (params) => electron_1.ipcRenderer.invoke('zalo:uploadVoiceFile', params),
        getQuickMessageList: (params) => electron_1.ipcRenderer.invoke('zalo:getQuickMessageList', params),
        addQuickMessage: (params) => electron_1.ipcRenderer.invoke('zalo:addQuickMessage', params),
        updateQuickMessage: (params) => electron_1.ipcRenderer.invoke('zalo:updateQuickMessage', params),
        removeQuickMessage: (params) => electron_1.ipcRenderer.invoke('zalo:removeQuickMessage', params),
        createNote: (params) => electron_1.ipcRenderer.invoke('zalo:createNote', params),
        editNote: (params) => electron_1.ipcRenderer.invoke('zalo:editNote', params),
        createReminder: (params) => electron_1.ipcRenderer.invoke('zalo:createReminder', params),
        editReminder: (params) => electron_1.ipcRenderer.invoke('zalo:editReminder', params),
        removeReminder: (params) => electron_1.ipcRenderer.invoke('zalo:removeReminder', params),
        getListReminder: (params) => electron_1.ipcRenderer.invoke('zalo:getListReminder', params),
        getReminder: (params) => electron_1.ipcRenderer.invoke('zalo:getReminder', params),
        sendSeenEvent: (params) => electron_1.ipcRenderer.invoke('zalo:sendSeenEvent', params),
        sendBankCard: (params) => electron_1.ipcRenderer.invoke('zalo:sendBankCard', params),
    },
    db: {
        getMessages: (params) => electron_1.ipcRenderer.invoke('db:getMessages', params),
        getMessagesAround: (params) => electron_1.ipcRenderer.invoke('db:getMessagesAround', params),
        getContacts: (zaloId) => electron_1.ipcRenderer.invoke('db:getContacts', { zaloId }),
        searchMessages: (params) => electron_1.ipcRenderer.invoke('db:searchMessages', params),
        getMediaMessages: (params) => electron_1.ipcRenderer.invoke('db:getMediaMessages', params),
        getFileMessages: (params) => electron_1.ipcRenderer.invoke('db:getFileMessages', params),
        getUnreadCount: (zaloId) => electron_1.ipcRenderer.invoke('db:getUnreadCount', { zaloId }),
        markAsRead: (params) => electron_1.ipcRenderer.invoke('db:markAsRead', params),
        markMessageRecalled: (params) => electron_1.ipcRenderer.invoke('db:markMessageRecalled', params),
        deleteMessages: (params) => electron_1.ipcRenderer.invoke('db:deleteMessages', params),
        updateContactProfile: (params) => electron_1.ipcRenderer.invoke('db:updateContactProfile', params),
        updateAccountPhone: (params) => electron_1.ipcRenderer.invoke('db:updateAccountPhone', params),
        updateReaction: (params) => electron_1.ipcRenderer.invoke('db:updateReaction', params),
        updateLocalPaths: (params) => electron_1.ipcRenderer.invoke('db:updateLocalPaths', params),
        getMessageById: (params) => electron_1.ipcRenderer.invoke('db:getMessageById', params),
        getStoragePath: () => electron_1.ipcRenderer.invoke('db:getStoragePath'),
        setStoragePath: (params) => electron_1.ipcRenderer.invoke('db:setStoragePath', params),
        selectStorageFolder: () => electron_1.ipcRenderer.invoke('db:selectStorageFolder'),
        getFriends: (params) => electron_1.ipcRenderer.invoke('db:getFriends', params),
        saveFriends: (params) => electron_1.ipcRenderer.invoke('db:saveFriends', params),
        isFriend: (params) => electron_1.ipcRenderer.invoke('db:isFriend', params),
        getFriendRequests: (params) => electron_1.ipcRenderer.invoke('db:getFriendRequests', params),
        saveFriendRequests: (params) => electron_1.ipcRenderer.invoke('db:saveFriendRequests', params),
        upsertFriendRequest: (params) => electron_1.ipcRenderer.invoke('db:upsertFriendRequest', params),
        removeFriendRequest: (params) => electron_1.ipcRenderer.invoke('db:removeFriendRequest', params),
        addFriend: (params) => electron_1.ipcRenderer.invoke('db:addFriend', params),
        removeFriend: (params) => electron_1.ipcRenderer.invoke('db:removeFriend', params),
        deleteConversation: (params) => electron_1.ipcRenderer.invoke('db:deleteConversation', params),
        getLinks: (params) => electron_1.ipcRenderer.invoke('db:getLinks', params),
        saveLink: (params) => electron_1.ipcRenderer.invoke('db:saveLink', params),
        getGroupMembers: (params) => electron_1.ipcRenderer.invoke('db:getGroupMembers', params),
        getAllGroupMembers: (params) => electron_1.ipcRenderer.invoke('db:getAllGroupMembers', params),
        saveGroupMembers: (params) => electron_1.ipcRenderer.invoke('db:saveGroupMembers', params),
        upsertGroupMember: (params) => electron_1.ipcRenderer.invoke('db:upsertGroupMember', params),
        removeGroupMember: (params) => electron_1.ipcRenderer.invoke('db:removeGroupMember', params),
        saveStickers: (params) => electron_1.ipcRenderer.invoke('db:saveStickers', params),
        getStickerById: (params) => electron_1.ipcRenderer.invoke('db:getStickerById', params),
        getRecentStickers: (params) => electron_1.ipcRenderer.invoke('db:getRecentStickers', params || {}),
        addRecentSticker: (params) => electron_1.ipcRenderer.invoke('db:addRecentSticker', params),
        markStickerUnsupported: (params) => electron_1.ipcRenderer.invoke('db:markStickerUnsupported', params),
        saveStickerPacks: (params) => electron_1.ipcRenderer.invoke('db:saveStickerPacks', params),
        getStickerPacks: (params) => electron_1.ipcRenderer.invoke('db:getStickerPacks', params || {}),
        getStickersByPackId: (params) => electron_1.ipcRenderer.invoke('db:getStickersByPackId', params),
        saveKeywordStickers: (params) => electron_1.ipcRenderer.invoke('db:saveKeywordStickers', params),
        getKeywordStickers: (params) => electron_1.ipcRenderer.invoke('db:getKeywordStickers', params),
        getStickersByIds: (params) => electron_1.ipcRenderer.invoke('db:getStickersByIds', params),
        getAllCachedPackSummaries: (params) => electron_1.ipcRenderer.invoke('db:getAllCachedPackSummaries', params || {}),
        getPinnedMessages: (params) => electron_1.ipcRenderer.invoke('db:getPinnedMessages', params),
        getMessagesByType: (params) => electron_1.ipcRenderer.invoke('db:getMessagesByType', params),
        pinMessage: (params) => electron_1.ipcRenderer.invoke('db:pinMessage', params),
        unpinMessage: (params) => electron_1.ipcRenderer.invoke('db:unpinMessage', params),
        bringPinnedToTop: (params) => electron_1.ipcRenderer.invoke('db:bringPinnedToTop', params),
        getLocalQuickMessages: (params) => electron_1.ipcRenderer.invoke('db:getLocalQuickMessages', params),
        upsertLocalQuickMessage: (params) => electron_1.ipcRenderer.invoke('db:upsertLocalQuickMessage', params),
        deleteLocalQuickMessage: (params) => electron_1.ipcRenderer.invoke('db:deleteLocalQuickMessage', params),
        bulkReplaceLocalQuickMessages: (params) => electron_1.ipcRenderer.invoke('db:bulkReplaceLocalQuickMessages', params),
        getAllLocalQuickMessages: () => electron_1.ipcRenderer.invoke('db:getAllLocalQuickMessages'),
        cloneLocalQuickMessages: (params) => electron_1.ipcRenderer.invoke('db:cloneLocalQuickMessages', params),
        setLocalQMActive: (params) => electron_1.ipcRenderer.invoke('db:setLocalQMActive', params),
        setLocalQMOrder: (params) => electron_1.ipcRenderer.invoke('db:setLocalQMOrder', params),
        // Local Labels
        getLocalLabels: (params) => electron_1.ipcRenderer.invoke('db:getLocalLabels', params),
        upsertLocalLabel: (params) => electron_1.ipcRenderer.invoke('db:upsertLocalLabel', params),
        deleteLocalLabel: (params) => electron_1.ipcRenderer.invoke('db:deleteLocalLabel', params),
        cloneLocalLabels: (params) => electron_1.ipcRenderer.invoke('db:cloneLocalLabels', params),
        getLocalLabelThreads: (params) => electron_1.ipcRenderer.invoke('db:getLocalLabelThreads', params),
        assignLocalLabelToThread: (params) => electron_1.ipcRenderer.invoke('db:assignLocalLabelToThread', params),
        removeLocalLabelFromThread: (params) => electron_1.ipcRenderer.invoke('db:removeLocalLabelFromThread', params),
        getThreadLocalLabels: (params) => electron_1.ipcRenderer.invoke('db:getThreadLocalLabels', params),
        setLocalLabelActive: (params) => electron_1.ipcRenderer.invoke('db:setLocalLabelActive', params),
        setLocalLabelOrder: (params) => electron_1.ipcRenderer.invoke('db:setLocalLabelOrder', params),
        setContactFlags: (params) => electron_1.ipcRenderer.invoke('db:setContactFlags', params),
        getContactsWithFlags: (params) => electron_1.ipcRenderer.invoke('db:getContactsWithFlags', params),
        setContactAlias: (params) => electron_1.ipcRenderer.invoke('db:setContactAlias', params),
        // Message Drafts
        upsertDraft: (params) => electron_1.ipcRenderer.invoke('db:upsertDraft', params),
        deleteDraft: (params) => electron_1.ipcRenderer.invoke('db:deleteDraft', params),
        getDraft: (params) => electron_1.ipcRenderer.invoke('db:getDraft', params),
        getDrafts: (params) => electron_1.ipcRenderer.invoke('db:getDrafts', params),
        deleteOldDrafts: (params) => electron_1.ipcRenderer.invoke('db:deleteOldDrafts', params || {}),
        // Bank Cards
        getBankCards: (params) => electron_1.ipcRenderer.invoke('db:getBankCards', params),
        upsertBankCard: (params) => electron_1.ipcRenderer.invoke('db:upsertBankCard', params),
        deleteBankCard: (params) => electron_1.ipcRenderer.invoke('db:deleteBankCard', params),
        // Local Pinned Conversations
        getLocalPinnedConversations: (params) => electron_1.ipcRenderer.invoke('db:getLocalPinnedConversations', params),
        setLocalPinnedConversation: (params) => electron_1.ipcRenderer.invoke('db:setLocalPinnedConversation', params),
    },
    // ─── CRM ─────────────────────────────────────────────────────────
    crm: {
        getNotes: (params) => electron_1.ipcRenderer.invoke('crm:getNotes', params),
        saveNote: (params) => electron_1.ipcRenderer.invoke('crm:saveNote', params),
        deleteNote: (params) => electron_1.ipcRenderer.invoke('crm:deleteNote', params),
        getContacts: (params) => electron_1.ipcRenderer.invoke('crm:getContacts', params),
        getContactStats: (params) => electron_1.ipcRenderer.invoke('crm:getContactStats', params),
        getCampaigns: (params) => electron_1.ipcRenderer.invoke('crm:getCampaigns', params),
        saveCampaign: (params) => electron_1.ipcRenderer.invoke('crm:saveCampaign', params),
        deleteCampaign: (params) => electron_1.ipcRenderer.invoke('crm:deleteCampaign', params),
        cloneCampaign: (params) => electron_1.ipcRenderer.invoke('crm:cloneCampaign', params),
        updateCampaignStatus: (params) => electron_1.ipcRenderer.invoke('crm:updateCampaignStatus', params),
        addCampaignContacts: (params) => electron_1.ipcRenderer.invoke('crm:addCampaignContacts', params),
        getCampaignContacts: (params) => electron_1.ipcRenderer.invoke('crm:getCampaignContacts', params),
        getSendLog: (params) => electron_1.ipcRenderer.invoke('crm:getSendLog', params),
        getQueueStatus: (params) => electron_1.ipcRenderer.invoke('crm:getQueueStatus', params),
        getCampaignStats: (params) => electron_1.ipcRenderer.invoke('crm:getCampaignStats', params),
        getActivityStats: (params) => electron_1.ipcRenderer.invoke('crm:getActivityStats', params),
    },
    // ─── Analytics / Reporting ──────────────────────────────────────────
    analytics: {
        dashboardOverview: (params) => electron_1.ipcRenderer.invoke('analytics:dashboardOverview', params),
        messageVolume: (params) => electron_1.ipcRenderer.invoke('analytics:messageVolume', params),
        peakHours: (params) => electron_1.ipcRenderer.invoke('analytics:peakHours', params),
        contactGrowth: (params) => electron_1.ipcRenderer.invoke('analytics:contactGrowth', params),
        contactSegmentation: (params) => electron_1.ipcRenderer.invoke('analytics:contactSegmentation', params),
        campaignComparison: (params) => electron_1.ipcRenderer.invoke('analytics:campaignComparison', params),
        friendRequests: (params) => electron_1.ipcRenderer.invoke('analytics:friendRequests', params),
        workflowAnalytics: (params) => electron_1.ipcRenderer.invoke('analytics:workflowAnalytics', params),
        aiAnalytics: (params) => electron_1.ipcRenderer.invoke('analytics:aiAnalytics', params),
        responseTime: (params) => electron_1.ipcRenderer.invoke('analytics:responseTime', params),
        labelUsage: (params) => electron_1.ipcRenderer.invoke('analytics:labelUsage', params),
    },
    // ─── File ────────────────────────────────────────────────────────
    file: {
        openDialog: (options) => electron_1.ipcRenderer.invoke('file:openDialog', options),
        saveImage: (params) => electron_1.ipcRenderer.invoke('file:saveImage', params),
        getAppDataPath: () => electron_1.ipcRenderer.invoke('file:getAppDataPath'),
        openPath: (filePath) => electron_1.ipcRenderer.invoke('file:openPath', filePath),
        showItemInFolder: (filePath) => electron_1.ipcRenderer.invoke('file:showItemInFolder', filePath),
        saveAs: (params) => electron_1.ipcRenderer.invoke('file:saveAs', params),
        saveTempBlob: (params) => electron_1.ipcRenderer.invoke('file:saveTempBlob', params),
        getVideoMeta: (params) => electron_1.ipcRenderer.invoke('file:getVideoMeta', params),
    },
    // ─── Workflow Engine ─────────────────────────────────────────────
    workflow: {
        list: () => electron_1.ipcRenderer.invoke('workflow:list'),
        get: (id) => electron_1.ipcRenderer.invoke('workflow:get', { id }),
        save: (workflow) => electron_1.ipcRenderer.invoke('workflow:save', { workflow }),
        delete: (id) => electron_1.ipcRenderer.invoke('workflow:delete', { id }),
        toggle: (id, enabled) => electron_1.ipcRenderer.invoke('workflow:toggle', { id, enabled }),
        runManual: (id, triggerData) => electron_1.ipcRenderer.invoke('workflow:runManual', { id, triggerData }),
        getLogs: (id, limit) => electron_1.ipcRenderer.invoke('workflow:getLogs', { id, limit }),
        deleteLogs: (id) => electron_1.ipcRenderer.invoke('workflow:deleteLogs', { id }),
        clone: (id, targetZaloId) => electron_1.ipcRenderer.invoke('workflow:clone', { id, targetZaloId }),
        cloneAll: (sourceZaloId, targetZaloId) => electron_1.ipcRenderer.invoke('workflow:cloneAll', { sourceZaloId, targetZaloId }),
    },
    // ─── App-level (badge, open thread) ─────────────────────────────
    app: {
        setBadge: (count) => electron_1.ipcRenderer.send('app:setBadge', count),
        openThread: (params) => electron_1.ipcRenderer.send('app:openThread', params),
        sendBadgeImage: (params) => electron_1.ipcRenderer.send('app:badgeImage', params),
        flashFrame: (active) => electron_1.ipcRenderer.send('app:flashFrame', { active }),
    },
    // ─── Auto-update ─────────────────────────────────────────────────
    update: {
        download: () => electron_1.ipcRenderer.send('update:download'),
        install: () => electron_1.ipcRenderer.send('update:install'),
    },
    // ─── Integration Hub ──────────────────────────────────────────────
    integration: {
        list: () => electron_1.ipcRenderer.invoke('integration:list'),
        get: (id) => electron_1.ipcRenderer.invoke('integration:get', { id }),
        save: (integration) => electron_1.ipcRenderer.invoke('integration:save', { integration }),
        delete: (id) => electron_1.ipcRenderer.invoke('integration:delete', { id }),
        toggle: (id, enabled) => electron_1.ipcRenderer.invoke('integration:toggle', { id, enabled }),
        test: (id) => electron_1.ipcRenderer.invoke('integration:test', { id }),
        execute: (id, action, params) => electron_1.ipcRenderer.invoke('integration:execute', { id, action, params }),
        executeByType: (type, action, params) => electron_1.ipcRenderer.invoke('integration:executeByType', { type, action, params }),
        getWebhookPort: () => electron_1.ipcRenderer.invoke('integration:getWebhookPort'),
    },
    // ─── AI Assistants ────────────────────────────────────────────────
    ai: {
        listAssistants: () => electron_1.ipcRenderer.invoke('ai:listAssistants'),
        getAssistant: (id) => electron_1.ipcRenderer.invoke('ai:getAssistant', { id }),
        getDefault: () => electron_1.ipcRenderer.invoke('ai:getDefault'),
        saveAssistant: (assistant) => electron_1.ipcRenderer.invoke('ai:saveAssistant', { assistant }),
        deleteAssistant: (id) => electron_1.ipcRenderer.invoke('ai:deleteAssistant', { id }),
        testAssistant: (id) => electron_1.ipcRenderer.invoke('ai:testAssistant', { id }),
        getFiles: (assistantId) => electron_1.ipcRenderer.invoke('ai:getFiles', { assistantId }),
        uploadFile: (assistantId, filePath) => electron_1.ipcRenderer.invoke('ai:uploadFile', { assistantId, filePath }),
        removeFile: (fileId) => electron_1.ipcRenderer.invoke('ai:removeFile', { fileId }),
        suggest: (assistantId, chatHistory) => electron_1.ipcRenderer.invoke('ai:suggest', { assistantId, chatHistory }),
        chat: (assistantId, messages, structured) => electron_1.ipcRenderer.invoke('ai:chat', { assistantId, messages, structured }),
        getAccountAssistant: (zaloId, role) => electron_1.ipcRenderer.invoke('ai:getAccountAssistant', { zaloId, role }),
        setAccountAssistant: (zaloId, role, assistantId) => electron_1.ipcRenderer.invoke('ai:setAccountAssistant', { zaloId, role, assistantId }),
        getAccountAssistants: (zaloId) => electron_1.ipcRenderer.invoke('ai:getAccountAssistants', { zaloId }),
        getUsageLogs: (opts) => electron_1.ipcRenderer.invoke('ai:getUsageLogs', opts || {}),
        getUsageStats: (opts) => electron_1.ipcRenderer.invoke('ai:getUsageStats', opts || {}),
    },
    // ─── Tunnel ───────────────────────────────────────────────────────
    tunnel: {
        start: () => electron_1.ipcRenderer.invoke('tunnel:start'),
        stop: () => electron_1.ipcRenderer.invoke('tunnel:stop'),
        status: () => electron_1.ipcRenderer.invoke('tunnel:status'),
    },
    // ─── Employee Management ───────────────────────────────────────────
    employee: {
        list: () => electron_1.ipcRenderer.invoke('employee:list'),
        getById: (employeeId) => electron_1.ipcRenderer.invoke('employee:getById', { employeeId }),
        create: (params) => electron_1.ipcRenderer.invoke('employee:create', params),
        update: (employeeId, updates) => electron_1.ipcRenderer.invoke('employee:update', { employeeId, updates }),
        delete: (employeeId) => electron_1.ipcRenderer.invoke('employee:delete', { employeeId }),
        setPermissions: (employeeId, permissions) => electron_1.ipcRenderer.invoke('employee:setPermissions', { employeeId, permissions }),
        getPermissions: (employeeId) => electron_1.ipcRenderer.invoke('employee:getPermissions', { employeeId }),
        assignAccounts: (employeeId, zaloIds) => electron_1.ipcRenderer.invoke('employee:assignAccounts', { employeeId, zaloIds }),
        getAssignedAccounts: (employeeId) => electron_1.ipcRenderer.invoke('employee:getAssignedAccounts', { employeeId }),
        getStats: (employeeId, sinceTs, untilTs) => electron_1.ipcRenderer.invoke('employee:getStats', { employeeId, sinceTs, untilTs }),
        getSessions: (employeeId, limit) => electron_1.ipcRenderer.invoke('employee:getSessions', { employeeId, limit }),
        login: (username, password) => electron_1.ipcRenderer.invoke('employee:login', { username, password }),
        validateToken: (token) => electron_1.ipcRenderer.invoke('employee:validateToken', { token }),
        setMode: (mode) => electron_1.ipcRenderer.invoke('employee:setMode', { mode }),
        getMode: () => electron_1.ipcRenderer.invoke('employee:getMode'),
        connectToBoss: (bossUrl, token) => electron_1.ipcRenderer.invoke('employee:connectToBoss', { bossUrl, token }),
        disconnectFromBoss: () => electron_1.ipcRenderer.invoke('employee:disconnectFromBoss'),
        getConnectionStatus: () => electron_1.ipcRenderer.invoke('employee:getConnectionStatus'),
        proxyAction: (channel, params) => electron_1.ipcRenderer.invoke('employee:proxyAction', { channel, params }),
        // Groups
        listGroups: () => electron_1.ipcRenderer.invoke('employee:listGroups'),
        createGroup: (name, color) => electron_1.ipcRenderer.invoke('employee:createGroup', { name, color }),
        updateGroup: (groupId, updates) => electron_1.ipcRenderer.invoke('employee:updateGroup', { groupId, updates }),
        deleteGroup: (groupId) => electron_1.ipcRenderer.invoke('employee:deleteGroup', { groupId }),
        // Analytics
        analyticsComparison: (sinceTs, untilTs) => electron_1.ipcRenderer.invoke('employee:analytics:comparison', { sinceTs, untilTs }),
        analyticsMessageTimeline: (sinceTs, untilTs) => electron_1.ipcRenderer.invoke('employee:analytics:messageTimeline', { sinceTs, untilTs }),
        analyticsOnlineTimeline: (sinceTs, untilTs) => electron_1.ipcRenderer.invoke('employee:analytics:onlineTimeline', { sinceTs, untilTs }),
        analyticsResponseDist: (sinceTs, untilTs) => electron_1.ipcRenderer.invoke('employee:analytics:responseDistribution', { sinceTs, untilTs }),
        analyticsHourlyActivity: (sinceTs, untilTs) => electron_1.ipcRenderer.invoke('employee:analytics:hourlyActivity', { sinceTs, untilTs }),
    },
    // ─── Workspace Management ────────────────────────────────────────
    workspace: {
        list: () => electron_1.ipcRenderer.invoke('workspace:list'),
        getActive: () => electron_1.ipcRenderer.invoke('workspace:getActive'),
        create: (params) => electron_1.ipcRenderer.invoke('workspace:create', params),
        update: (id, updates) => electron_1.ipcRenderer.invoke('workspace:update', { id, updates }),
        delete: (id) => electron_1.ipcRenderer.invoke('workspace:delete', { id }),
        switch: (id) => electron_1.ipcRenderer.invoke('workspace:switch', { id }),
        isMulti: () => electron_1.ipcRenderer.invoke('workspace:isMulti'),
        getDbPath: (id) => electron_1.ipcRenderer.invoke('workspace:getDbPath', { id }),
        connectRemote: (id, bossUrl, token) => electron_1.ipcRenderer.invoke('workspace:connectRemote', { id, bossUrl, token }),
        disconnectRemote: (id) => electron_1.ipcRenderer.invoke('workspace:disconnectRemote', { id }),
        getConnectionStatus: (id) => electron_1.ipcRenderer.invoke('workspace:getConnectionStatus', { id }),
        getAllStatuses: () => electron_1.ipcRenderer.invoke('workspace:getAllStatuses'),
        loginRemote: (bossUrl, username, password) => electron_1.ipcRenderer.invoke('workspace:loginRemote', { bossUrl, username, password }),
    },
    // ─── Relay Server (Boss) ──────────────────────────────────────────
    relay: {
        startServer: (port) => electron_1.ipcRenderer.invoke('relay:startServer', { port }),
        stopServer: () => electron_1.ipcRenderer.invoke('relay:stopServer'),
        getServerStatus: () => electron_1.ipcRenderer.invoke('relay:getServerStatus'),
        kickEmployee: (employeeId) => electron_1.ipcRenderer.invoke('relay:kickEmployee', { employeeId }),
    },
    // ─── Data Sync (Employee) ──────────────────────────────────────────
    sync: {
        requestFullSync: (zaloIds) => electron_1.ipcRenderer.invoke('sync:requestFullSync', { zaloIds }),
        requestDeltaSync: (sinceTs) => electron_1.ipcRenderer.invoke('sync:requestDeltaSync', { sinceTs }),
        resetEmployeeDB: (zaloIds) => electron_1.ipcRenderer.invoke('sync:resetEmployeeDB', { zaloIds }),
        getStatus: () => electron_1.ipcRenderer.invoke('sync:getStatus'),
        requestMedia: (filePath) => electron_1.ipcRenderer.invoke('sync:requestMedia', { filePath }),
    },
    // ─── Facebook ─────────────────────────────────────────────────────
    fb: {
        addAccount: (params) => electron_1.ipcRenderer.invoke('fb:addAccount', params),
        removeAccount: (params) => electron_1.ipcRenderer.invoke('fb:removeAccount', params),
        updateCookie: (params) => electron_1.ipcRenderer.invoke('fb:updateCookie', params),
        refreshProfile: (params) => electron_1.ipcRenderer.invoke('fb:refreshProfile', params),
        getAccounts: () => electron_1.ipcRenderer.invoke('fb:getAccounts'),
        connect: (params) => electron_1.ipcRenderer.invoke('fb:connect', params),
        disconnect: (params) => electron_1.ipcRenderer.invoke('fb:disconnect', params),
        checkHealth: (params) => electron_1.ipcRenderer.invoke('fb:checkHealth', params),
        sendMessage: (params) => electron_1.ipcRenderer.invoke('fb:sendMessage', params),
        sendAttachment: (params) => electron_1.ipcRenderer.invoke('fb:sendAttachment', params),
        sendAttachments: (params) => electron_1.ipcRenderer.invoke('fb:sendAttachments', params),
        unsendMessage: (params) => electron_1.ipcRenderer.invoke('fb:unsendMessage', params),
        addReaction: (params) => electron_1.ipcRenderer.invoke('fb:addReaction', params),
        getThreads: (params) => electron_1.ipcRenderer.invoke('fb:getThreads', params),
        getMessages: (params) => electron_1.ipcRenderer.invoke('fb:getMessages', params),
        markAsRead: (params) => electron_1.ipcRenderer.invoke('fb:markAsRead', params),
        changeThreadName: (params) => electron_1.ipcRenderer.invoke('fb:changeThreadName', params),
        changeThreadEmoji: (params) => electron_1.ipcRenderer.invoke('fb:changeThreadEmoji', params),
        changeNickname: (params) => electron_1.ipcRenderer.invoke('fb:changeNickname', params),
        loginWithCredentials: (params) => electron_1.ipcRenderer.invoke('fb:loginWithCredentials', params),
    },
    // ─── ERP ─────────────────────────────────────────────────────────
    erp: {
        // Projects
        projectList: (params) => electron_1.ipcRenderer.invoke('erp:project:list', params),
        projectCreate: (params) => electron_1.ipcRenderer.invoke('erp:project:create', params),
        projectUpdate: (params) => electron_1.ipcRenderer.invoke('erp:project:update', params),
        projectDelete: (params) => electron_1.ipcRenderer.invoke('erp:project:delete', params),
        // Tasks
        taskList: (params) => electron_1.ipcRenderer.invoke('erp:task:list', params),
        taskGet: (params) => electron_1.ipcRenderer.invoke('erp:task:get', params),
        taskCreate: (params) => electron_1.ipcRenderer.invoke('erp:task:create', params),
        taskUpdate: (params) => electron_1.ipcRenderer.invoke('erp:task:update', params),
        taskUpdateStatus: (params) => electron_1.ipcRenderer.invoke('erp:task:updateStatus', params),
        taskAssign: (params) => electron_1.ipcRenderer.invoke('erp:task:assign', params),
        taskDelete: (params) => electron_1.ipcRenderer.invoke('erp:task:delete', params),
        taskAddChecklist: (params) => electron_1.ipcRenderer.invoke('erp:task:addChecklist', params),
        taskToggleChecklist: (params) => electron_1.ipcRenderer.invoke('erp:task:toggleChecklist', params),
        taskAddComment: (params) => electron_1.ipcRenderer.invoke('erp:task:addComment', params),
        taskEditComment: (params) => electron_1.ipcRenderer.invoke('erp:task:editComment', params),
        taskDeleteComment: (params) => electron_1.ipcRenderer.invoke('erp:task:deleteComment', params),
        taskListMyInbox: (params) => electron_1.ipcRenderer.invoke('erp:task:listMyInbox', params),
        // Calendar
        calendarListEvents: (params) => electron_1.ipcRenderer.invoke('erp:calendar:listEvents', params),
        calendarCreate: (params) => electron_1.ipcRenderer.invoke('erp:calendar:createEvent', params),
        calendarUpdate: (params) => electron_1.ipcRenderer.invoke('erp:calendar:updateEvent', params),
        calendarDelete: (params) => electron_1.ipcRenderer.invoke('erp:calendar:deleteEvent', params),
        calendarCheckConflict: (params) => electron_1.ipcRenderer.invoke('erp:calendar:checkConflict', params),
        // Notes
        noteListFolders: (params) => electron_1.ipcRenderer.invoke('erp:note:listFolders', params),
        noteCreateFolder: (params) => electron_1.ipcRenderer.invoke('erp:note:createFolder', params),
        noteRenameFolder: (params) => electron_1.ipcRenderer.invoke('erp:note:renameFolder', params),
        noteDeleteFolder: (params) => electron_1.ipcRenderer.invoke('erp:note:deleteFolder', params),
        noteList: (params) => electron_1.ipcRenderer.invoke('erp:note:list', params),
        noteGet: (params) => electron_1.ipcRenderer.invoke('erp:note:get', params),
        noteCreate: (params) => electron_1.ipcRenderer.invoke('erp:note:create', params),
        noteUpdate: (params) => electron_1.ipcRenderer.invoke('erp:note:update', params),
        noteDelete: (params) => electron_1.ipcRenderer.invoke('erp:note:delete', params),
        notePin: (params) => electron_1.ipcRenderer.invoke('erp:note:pin', params),
        noteListTags: () => electron_1.ipcRenderer.invoke('erp:note:listTags'),
        noteCreateTag: (params) => electron_1.ipcRenderer.invoke('erp:note:createTag', params),
        noteAddTag: (params) => electron_1.ipcRenderer.invoke('erp:note:addTag', params),
        noteRemoveTag: (params) => electron_1.ipcRenderer.invoke('erp:note:removeTag', params),
        noteVersions: (params) => electron_1.ipcRenderer.invoke('erp:note:versions', params),
        noteRestoreVersion: (params) => electron_1.ipcRenderer.invoke('erp:note:restoreVersion', params),
        noteShare: (params) => electron_1.ipcRenderer.invoke('erp:note:share', params),
        noteListShares: (params) => electron_1.ipcRenderer.invoke('erp:note:listShares', params),
        // Task watchers/dependencies (Phase 2)
        taskAddWatcher: (params) => electron_1.ipcRenderer.invoke('erp:task:addWatcher', params),
        taskRemoveWatcher: (params) => electron_1.ipcRenderer.invoke('erp:task:removeWatcher', params),
        taskAddDependency: (params) => electron_1.ipcRenderer.invoke('erp:task:addDependency', params),
        taskRemoveDependency: (params) => electron_1.ipcRenderer.invoke('erp:task:removeDependency', params),
        // Calendar respond (Phase 2)
        calendarRespond: (params) => electron_1.ipcRenderer.invoke('erp:calendar:respond', params),
        // HRM (Phase 2)
        departmentList: () => electron_1.ipcRenderer.invoke('erp:department:list'),
        departmentCreate: (params) => electron_1.ipcRenderer.invoke('erp:department:create', params),
        departmentUpdate: (params) => electron_1.ipcRenderer.invoke('erp:department:update', params),
        departmentDelete: (params) => electron_1.ipcRenderer.invoke('erp:department:delete', params),
        positionList: () => electron_1.ipcRenderer.invoke('erp:position:list'),
        positionCreate: (params) => electron_1.ipcRenderer.invoke('erp:position:create', params),
        positionUpdate: (params) => electron_1.ipcRenderer.invoke('erp:position:update', params),
        positionDelete: (params) => electron_1.ipcRenderer.invoke('erp:position:delete', params),
        employeeGetProfile: (params) => electron_1.ipcRenderer.invoke('erp:employee:getProfile', params),
        employeeUpdateProfile: (params) => electron_1.ipcRenderer.invoke('erp:employee:updateProfile', params),
        employeeListByDepartment: (params) => electron_1.ipcRenderer.invoke('erp:employee:listByDepartment', params),
        employeeDeleteProfile: (params) => electron_1.ipcRenderer.invoke('erp:employee:deleteProfile', params),
        attendanceCheckIn: (params) => electron_1.ipcRenderer.invoke('erp:attendance:checkIn', params),
        attendanceCheckOut: (params) => electron_1.ipcRenderer.invoke('erp:attendance:checkOut', params),
        attendanceToday: () => electron_1.ipcRenderer.invoke('erp:attendance:today'),
        attendanceList: (params) => electron_1.ipcRenderer.invoke('erp:attendance:list', params),
        leaveCreate: (params) => electron_1.ipcRenderer.invoke('erp:leave:create', params),
        leaveListMy: () => electron_1.ipcRenderer.invoke('erp:leave:listMy'),
        leaveListPending: () => electron_1.ipcRenderer.invoke('erp:leave:listPending'),
        leaveDecide: (params) => electron_1.ipcRenderer.invoke('erp:leave:decide', params),
        leaveCancel: (params) => electron_1.ipcRenderer.invoke('erp:leave:cancel', params),
        licenseSeatStatus: () => electron_1.ipcRenderer.invoke('erp:license:seatStatus'),
        // Notifications
        notifyListInbox: (params) => electron_1.ipcRenderer.invoke('erp:notify:listInbox', params),
        notifyMarkRead: (params) => electron_1.ipcRenderer.invoke('erp:notify:markRead', params),
        notifyMarkAllRead: (params) => electron_1.ipcRenderer.invoke('erp:notify:markAllRead', params),
        notifyUnreadCount: (params) => electron_1.ipcRenderer.invoke('erp:notify:unreadCount', params),
    },
    on: (channel, callback) => {
        const validChannels = [
            'event:message',
            'event:connected',
            'event:disconnected',
            'event:reaction',
            'event:friendRequest',
            'event:friendAccepted',
            'event:groupEvent',
            'event:groupInfoUpdate',
            'event:undo',
            'event:delete',
            'event:reminder',
            'event:localPath',
            'event:listenerDead',
            'event:pinsUpdated',
            'event:typing',
            'event:seen',
            'qr:update',
            'update:available',
            'update:progress',
            'update:downloaded',
            'update:error',
            'app:openThread',
            'app:windowFocus',
            'app:drawBadge',
            'crm:queueUpdate',
            'crm:queueStatus',
            'crm:campaignDone',
            'workflow:executed',
            'db:copyProgress',
            'integration:webhook',
            'integration:payment',
            'tunnel:changed',
            'relay:employeeListUpdate',
            'relay:messageSentByEmployee',
            'sync:progress',
            'workspace:switched',
            'workspace:connectionStatus',
            'workspace:initialState',
            'workspace:accountAccessUpdate',
            // ─── Facebook events ─────────────────────────────────────────────
            'fb:onMessage',
            'fb:onReaction',
            'fb:onUnsend',
            'fb:onDisconnect',
            'fb:onReconnect',
            'fb:onConnectionStatus',
            // ─── ERP events ──────────────────────────────────────────────────
            'erp:event:taskCreated',
            'erp:event:taskUpdated',
            'erp:event:taskDeleted',
            'erp:event:commentAdded',
            'erp:event:projectCreated',
            'erp:event:projectUpdated',
            'erp:event:projectDeleted',
            'erp:event:calendarEventCreated',
            'erp:event:calendarEventUpdated',
            'erp:event:calendarEventDeleted',
            'erp:event:noteCreated',
            'erp:event:noteUpdated',
            'erp:event:noteDeleted',
            'erp:event:notification',
            'erp:event:reminder',
            'erp:event:leaveCreated',
            'erp:event:leaveDecided',
            'erp:event:attendanceUpdated',
            'erp:event:noteShared',
            'erp:event:departmentUpdated',
            'erp:event:employeeProfileUpdated',
        ];
        if (validChannels.includes(channel)) {
            const subscription = (_event, ...args) => callback(...args);
            electron_1.ipcRenderer.on(channel, subscription);
            return () => electron_1.ipcRenderer.removeListener(channel, subscription);
        }
        return () => { };
    },
    removeAllListeners: (channel) => {
        electron_1.ipcRenderer.removeAllListeners(channel);
    },
});
//# sourceMappingURL=preload.js.map